version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - './volumes:/volumes'
            - './containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '443:443'
            - '80:80'
        links:
            - node
    node:
        build: ./containers/node/16/.
        expose:
            - "3000"
        ports: 
            - "3000:3000"
        volumes:
            - './containers/node/16/app:/home/node/app'