version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - './volumes:/volumes'
            - './containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '443:443'
            - '80:80'
        links:
            - node
    node:
        build: ./containers/node/14/.
        expose:
            - "3000"
            - "4200"
            - "4300"
        ports: 
            - "3000:3000"
            - "4200:4200"
            - "4300:4300"
        volumes:
            - '~/.ssh:/root/.ssh'
            - './volumes:/volumes'