---
version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
    - "./volumes:/volumes"
    - "./containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
    - 443:443
    - 80:80
    links:
    - node
  node:
    build: "./containers/node/14/."
    expose:
    - '3000'
    - '4200'
    - '4300'
    - '8000'
    - '8001'
    - '8002'
    - '8003'
    - '8004'
    - '8005'
    - '8006'
    - '8007'
    - '8008'
    - '8009'
    - '8010'
    - '8011'
    - '8012'
    - '8013'
    - '8014'
    ports:
    - 3000:3000
    - 4200:4200
    - 4300:4300
    - 8000:8000
    - 8001:8001
    - 8002:8002
    - 8003:8003
    - 8004:8004
    - 8005:8005
    - 8006:8006
    - 8007:8007
    - 8008:8008
    - 8009:8009
    - 8010:8010
    - 8011:8011
    - 8012:8012
    - 8013:8013
    - 8014:8014
    volumes:
    - "./containers/node/14/app1:/app1"
    - "~/.ssh:/root/.ssh"
    - "./volumes:/volumes"
  mongo:
    image: mongo
    container_name: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=passw0rd1
    - MONGO_INITDB_DATABASE=auth
    ports:
    - 27017:27017
    volumes:
    - "./tmp/mongo:/data/db"
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
    - 8081:8081
    environment:
    - ME_CONFIG_MONGODB_URL=mongodb://admin:passw0rd1@mongo:27017/
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=passw0rd1
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=passw0rd1
    links:
    - mongo